In [75]:
import sys
import os

sys.path.append(os.path.abspath('..'))

In [2]:
import pandas as pd

# Cargar dataset
df = pd.read_csv('../data/online_retail.csv', encoding='ISO-8859-1')

# Vista rápida
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
df.info()

df.isnull().sum()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [4]:
df[df['Quantity'] < 0].head()

df[df['UnitPrice'] < 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [5]:
df['tipo_transaccion'] = 'venta'

df.loc[df['Quantity'] < 0, 'tipo_transaccion'] = 'devolucion'
df.loc[df['UnitPrice'] < 0, 'tipo_transaccion'] = 'error_precio'

In [6]:
df['tipo_transaccion'].value_counts()

tipo_transaccion
venta           531283
devolucion       10624
error_precio         2
Name: count, dtype: int64

In [7]:
df[df['tipo_transaccion'] == 'devolucion'].groupby('Country')['Quantity'].count().sort_values(ascending=False)

Country
United Kingdom        9192
Germany                453
EIRE                   302
France                 149
USA                    112
Australia               74
Spain                   48
Italy                   45
Belgium                 38
Japan                   37
Switzerland             35
Portugal                18
Malta                   15
Norway                  14
Poland                  11
Sweden                  11
Channel Islands         10
Finland                 10
Denmark                  9
Cyprus                   8
Netherlands              8
Singapore                7
Czech Republic           5
Hong Kong                4
Austria                  3
Israel                   2
Greece                   1
European Community       1
Bahrain                  1
Saudi Arabia             1
Name: Quantity, dtype: int64

In [8]:
ventas_por_pais = df[df['tipo_transaccion'] == 'venta'].groupby('Country').size()

devoluciones_por_pais = df[df['tipo_transaccion'] == 'devolucion'].groupby('Country').size()

tasa_devolucion = (devoluciones_por_pais / ventas_por_pais).sort_values(ascending=False)

tasa_devolucion.head(10)

Country
USA               0.625698
Czech Republic    0.200000
Malta             0.133929
Japan             0.115265
Saudi Arabia      0.111111
Australia         0.062447
Italy             0.059367
Bahrain           0.055556
Germany           0.050100
EIRE              0.038257
dtype: float64

In [9]:
df_usa = df[df['Country'] == 'USA']
df_usa[df_usa['tipo_transaccion'] == 'devolucion']['Description'].value_counts().head(10)

Description
CARD DOLLY GIRL                    2
TEA PARTY BIRTHDAY CARD            2
SPACEBOY CHILDRENS BOWL            1
DOLLY GIRL CHILDRENS BOWL          1
CHILDRENS CUTLERY SPACEBOY         1
CHILDRENS CUTLERY CIRCUS PARADE    1
CHILDRENS CUTLERY DOLLY GIRL       1
VINTAGE DONKEY TAIL GAME           1
SMALL CERAMIC TOP STORAGE JAR      1
MEDIUM CERAMIC TOP STORAGE JAR     1
Name: count, dtype: int64

In [10]:
ventas_producto = df[df['tipo_transaccion'] == 'venta'].groupby('Description').size()

devoluciones_producto = df[df['tipo_transaccion'] == 'devolucion'].groupby('Description').size()

tasa_producto = (devoluciones_producto / ventas_producto).sort_values(ascending=False)

tasa_producto.head(10)

Description
damaged                        42.000000
SAMPLES                        30.500000
AMAZON FEE                     16.000000
?                               6.833333
check                           3.076923
BLUE PADDED SOFT MOBILE         3.000000
Bank Charges                    2.083333
PINK SMALL GLASS CAKE STAND     2.000000
BLACK CHERRY LIGHTS             2.000000
PINK CHERRY LIGHTS              2.000000
dtype: float64

In [11]:
invalidos = ['damaged', 'SAMPLES', 'AMAZON FEE', '?', 'check', 'Bank Charges']

df_clean = df[~df['Description'].isin(invalidos)]

In [12]:
ventas_producto = df_clean[df_clean['tipo_transaccion'] == 'venta'].groupby('Description').size()

devoluciones_producto = df_clean[df_clean['tipo_transaccion'] == 'devolucion'].groupby('Description').size()

tasa_producto = (devoluciones_producto / ventas_producto).sort_values(ascending=False)

tasa_producto.head(10)

Description
BLUE PADDED SOFT MOBILE                3.0
PINK SMALL GLASS CAKE STAND            2.0
BLACK CHERRY LIGHTS                    2.0
PINK CHERRY LIGHTS                     2.0
WOODEN BOX ADVENT CALENDAR             1.6
HANGING RIDGE GLASS T-LIGHT HOLDER     1.5
wrongly coded 20713                    1.0
incorrectly credited C550456 see 47    1.0
WHITE BEADED GARLAND STRING 20LIGHT    1.0
PAPER CRAFT , LITTLE BIRDIE            1.0
dtype: float64

In [63]:
df = df.dropna(subset=['CustomerID'])

In [64]:
from sqlalchemy import create_engine

def get_engine():
    return create_engine(
        "postgresql://jhan:1234@localhost:5432/retail_db"
    )

In [65]:
import pandas as pd

def extract_data(path):
    df = pd.read_csv(path, encoding='ISO-8859-1')
    return df

In [66]:
import pandas as pd

def clean_data(df):

    # =========================
    # 1. NORMALIZAR COLUMNAS
    # =========================
    df.columns = df.columns.str.strip().str.lower()

    # =========================
    # 2. ELIMINAR NULOS CLAVE
    # =========================
    df = df.dropna(subset=['customerid', 'stockcode'])

    # =========================
    # 3. TIPOS CORRECTOS
    # =========================
    df['customerid'] = df['customerid'].astype(int)
    df['stockcode'] = df['stockcode'].astype(str)

    df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
    df['unitprice'] = pd.to_numeric(df['unitprice'], errors='coerce')

    df = df.dropna(subset=['quantity', 'unitprice'])

    # =========================
    # 4. FILTROS DE NEGOCIO
    # =========================
    df = df[df['quantity'] > 0]
    df = df[df['unitprice'] > 0]

    # =========================
    # 5. FECHA
    # =========================
    df['invoicedate'] = pd.to_datetime(df['invoicedate'])

    # =========================
    # 6. MÉTRICAS
    # =========================
    df['totalprice'] = df['quantity'] * df['unitprice']

    return df


# =========================
# DIMENSIONES
# =========================

def create_dim_customer(df):
    dim = (
        df.groupby('customerid')['country']
        .agg(lambda x: x.mode()[0])
        .reset_index()
    )

    dim.columns = ['customer_id', 'country']

    return dim


def create_dim_product(df):
    dim = df[['stockcode', 'description']].drop_duplicates()

    dim.columns = ['stock_code', 'description']

    return dim


def create_fact_sales(df):
    fact = df[['invoiceno', 'stockcode', 'quantity',
               'unitprice', 'totalprice',
               'invoicedate', 'customerid']]

    fact.columns = ['invoice_no', 'stock_code', 'quantity',
                    'unit_price', 'total_price',
                    'invoice_date', 'customer_id']

    return fact

In [67]:
from sqlalchemy import text

def reset_tables(engine):
    with engine.connect() as conn:
        conn.execute(text("""
            DROP TABLE IF EXISTS fact_sales CASCADE;
            DROP TABLE IF EXISTS dim_product CASCADE;
            DROP TABLE IF EXISTS dim_customer CASCADE;
        """))


def load_data(engine, dim_customer, dim_product, fact_sales):

    dim_customer.to_sql('dim_customer', engine, index=False)
    dim_product.to_sql('dim_product', engine, index=False)
    fact_sales.to_sql('fact_sales', engine, index=False)


def create_constraints(engine):
    with engine.connect() as conn:

        # PRIMARY KEYS
        conn.execute(text("""
            ALTER TABLE dim_customer 
            ADD CONSTRAINT dim_customer_pk PRIMARY KEY (customer_id);
        """))

        conn.execute(text("""
            ALTER TABLE dim_product 
            ADD CONSTRAINT dim_product_pk PRIMARY KEY (stock_code);
        """))

        # FOREIGN KEYS
        conn.execute(text("""
            ALTER TABLE fact_sales
            ADD CONSTRAINT fk_customer
            FOREIGN KEY (customer_id)
            REFERENCES dim_customer(customer_id);
        """))

        conn.execute(text("""
            ALTER TABLE fact_sales
            ADD CONSTRAINT fk_product
            FOREIGN KEY (stock_code)
            REFERENCES dim_product(stock_code);
        """))

In [69]:
import sys
import os

# Ajusta esta ruta a tu proyecto real
sys.path.append(os.path.abspath('..'))

In [71]:
sys.path.append('C:/Users/User/retail_project')

In [74]:
import os

print(os.getcwd())
print(os.listdir())

/home/jhanph/online-retail-project/notebooks
['eda_retail.ipynb']

In [78]:
import os

print(os.listdir('..'))

['data', 'src', '.gitignore', 'notebooks', '.git']

In [79]:
import os

print(os.path.exists('../config/db_config.py'))

False

In [86]:
import pandas as pd

def extract_data(path):
    df = pd.read_csv(path, encoding='ISO-8859-1')
    return df

In [83]:
import pandas as pd

def clean_data(df):

    df.columns = df.columns.str.strip().str.lower()

    df = df.dropna(subset=['customerid', 'stockcode'])

    df['customerid'] = df['customerid'].astype(int)
    df['stockcode'] = df['stockcode'].astype(str)

    df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
    df['unitprice'] = pd.to_numeric(df['unitprice'], errors='coerce')

    df = df.dropna(subset=['quantity', 'unitprice'])

    df = df[df['quantity'] > 0]
    df = df[df['unitprice'] > 0]

    df['invoicedate'] = pd.to_datetime(df['invoicedate'])

    df['totalprice'] = df['quantity'] * df['unitprice']

    return df


def create_dim_customer(df):
    dim = (
        df.groupby('customerid')['country']
        .agg(lambda x: x.mode()[0])
        .reset_index()
    )
    dim.columns = ['customer_id', 'country']
    return dim


def create_dim_product(df):
    dim = df[['stockcode', 'description']].drop_duplicates()
    dim.columns = ['stock_code', 'description']
    return dim


def create_fact_sales(df):
    fact = df[['invoiceno', 'stockcode', 'quantity',
               'unitprice', 'totalprice',
               'invoicedate', 'customerid']]

    fact.columns = ['invoice_no', 'stock_code', 'quantity',
                    'unit_price', 'total_price',
                    'invoice_date', 'customer_id']

    return fact

In [84]:
from sqlalchemy import text

def reset_tables(engine):
    with engine.connect() as conn:
        conn.execute(text("""
            DROP TABLE IF EXISTS fact_sales CASCADE;
            DROP TABLE IF EXISTS dim_product CASCADE;
            DROP TABLE IF EXISTS dim_customer CASCADE;
        """))


def load_data(engine, dim_customer, dim_product, fact_sales):

    dim_customer.to_sql('dim_customer', engine, index=False)
    dim_product.to_sql('dim_product', engine, index=False)
    fact_sales.to_sql('fact_sales', engine, index=False)


def create_constraints(engine):
    with engine.connect() as conn:

        conn.execute(text("""
            ALTER TABLE dim_customer 
            ADD PRIMARY KEY (customer_id);
        """))

        conn.execute(text("""
            ALTER TABLE dim_product 
            ADD PRIMARY KEY (stock_code);
        """))

        conn.execute(text("""
            ALTER TABLE fact_sales
            ADD CONSTRAINT fk_customer
            FOREIGN KEY (customer_id)
            REFERENCES dim_customer(customer_id);
        """))

        conn.execute(text("""
            ALTER TABLE fact_sales
            ADD CONSTRAINT fk_product
            FOREIGN KEY (stock_code)
            REFERENCES dim_product(stock_code);
        """))

In [88]:
import src.extract
print(dir(src.extract))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']

In [89]:
from src.extract import extract_data
print("OK")

ImportError: cannot import name 'extract_data' from 'src.extract' (/home/jhanph/online-retail-project/src/extract.py)

In [90]:
from config.db_config import get_engine
from src.extract import extract_data
from src.transform import clean_data, create_dim_customer, create_dim_product, create_fact_sales
from src.load import reset_tables, load_data, create_constraints

engine = get_engine()

df = extract_data('data/raw/online_retail.csv')

df_clean = clean_data(df)

dim_customer = create_dim_customer(df_clean)
dim_product = create_dim_product(df_clean)
fact_sales = create_fact_sales(df_clean)

reset_tables(engine)
load_data(engine, dim_customer, dim_product, fact_sales)
create_constraints(engine)

print("Pipeline completo 🚀")

ImportError: cannot import name 'extract_data' from 'src.extract' (/home/jhanph/online-retail-project/src/extract.py)